;(function($){
	/**
	 * [头部header和右侧菜单栏]
	 * @type {[type]}
	 */
	var head = $("<div class='header'>"
					+"<a href='index.html'>"
						+"<img src='images/logo_01.png' alt='壹杯加咖啡' class='header-left' />"
					+"</a>"
					+"<ul class='header-right'>"
						+"<li></li>"
						+"<li></li>"
						+"<li></li>"
					+"</ul>"
				+"</div>"
				+"<nav class='menu'>"
					+"<div class='menu-btn'>"
						+"<ul class='menu-btn-groups'>"
							+"<li></li>"
							+"<li></li>"
							+"<li></li>"
						+"</ul>"
					+"</div>"
					+"<ul class='menu-level' id='menu-level'>"
						+"<li class='menu-level-list first'>"
							+"<a href='index.html' class='menu-level-links none-shadow'>"
								+"<img src='images/title_pointer.png' alt='首页' class='menu-level-pics' />"
								+"<span>首页</span>"
							+"</a>"
						+"</li>"
						+"<li class='menu-level-list has-child'>"
							+"<a href='javascript:;' class='menu-level-links'>"
								+"<img src='images/title_pointer.png' alt='关于品牌' class='menu-level-pics' />"
								+"<span>关于品牌</span>"
							+"</a>"
							+"<ul class='menu-level2'>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='aboutBrand.html' class='menu-level2-links'>公司简介</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='aboutBrand.html#brand-introduce' class='menu-level2-links'>品牌介绍</a>"
								+"</li>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='aboutBrand.html#partner' class='menu-level2-links'>战略合作伙伴</a>"
								+"</li>"
							+"</ul>"
						+"</li>"
						+"<li class='menu-level-list has-child'>"
							+"<a href='javascript:;' class='menu-level-links'>"
								+"<img src='images/title_pointer.png' alt='品牌项目' class='menu-level-pics' />"
								+"<span>品牌项目</span>"
							+"</a>"
							+"<ul class='menu-level2'>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='brandProject.html' class='menu-level2-links'>咖啡连锁店</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='brandProject.html#one-space' class='menu-level2-links'>壹+空间</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='brandProject.html#training-college' class='menu-level2-links'>培训学院</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='brandProject.html#coffee-bus' class='menu-level2-links'>移动咖啡车</a>"
								+"</li>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='brandProject.html#online-platform' class='menu-level2-links'>网上支持平台</a>"
								+"</li>"
							+"</ul>"
						+"</li>"
						+"<li class='menu-level-list has-child store-image-groups'>"
							+"<a href='javascript:;' class='menu-level-links'>"
								+"<img src='images/title_pointer.png' alt='门店形象' class='menu-level-pics' />"
								+"<span>门店形象</span>"
							+"</a>"
							+"<ul class='menu-level2'>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='storeImage.html' class='menu-level2-links'>旗舰店</a>"
								+"</li>"
								+"<li class='menu-level2-list mini-store-list'>"
									+"<a href='storeImage.html#mini-store' class='menu-level2-links'>迷你店</a>"
								+"</li>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='storeImage.html#standard-store' class='menu-level2-links'>标准店</a>"
								+"</li>"
							+"</ul>"
						+"</li>"
						+"<li class='menu-level-list has-child'>"
							+"<a href='javascript:;' class='menu-level-links'>"
								+"<img src='images/title_pointer.png' alt='加盟资讯' class='menu-level-pics' />"
								+"<span>加盟资讯</span>"
							+"</a>"
							+"<ul class='menu-level2'>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='joinInformation.html' class='menu-level2-links'>加盟流程</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='joinInformation.html#assist-service' class='menu-level2-links'>协助服务</a>"
								+"</li>"
								+"<li class='menu-level2-list'>"
									+"<a href='joinInformation.html#join-cost' class='menu-level2-links'>加盟费用</a>"
								+"</li>"
								+"<li class='menu-level2-list tail'>"
									+"<a href='javascript:;' class='menu-level2-links'>在线预约</a>"
								+"</li>"
							+"</ul>"
						+"</li>"
						+"<li class='menu-level-list'>"
							+"<a href='joinUs.html' class='menu-level-links none-shadow'>"
								+"<img src='images/title_pointer.png' alt='加入我们' class='menu-level-pics' />"
								+"<span>加入我们</span>"
							+"</a>"
						+"</li>"
						+"<li class='menu-level-list'>"
							+"<a href='message.html' class='menu-level-links none-shadow'>"
								+"<img src='images/title_pointer.png' alt='留言咨询' class='menu-level-pics' />"
								+"<span>留言咨询</span>"
							+"</a>"
						+"</li>"
						+"<li class='menu-level-list'>"
							+"<a href='javascript:;' class='menu-level-links none-shadow'>"
								+"<img src='images/shop_icon.png' alt='壹杯加商城' class='menu-level-shop' />"
								+"<span>壹杯加商城</span>"
							+"</a>"
						+"</li>"
					+"</ul>"
				+"</nav>");
	$('body').prepend(head);
	
})(jQuery);