document.writeln("<!-- 壹杯加咖啡标题栏模块 -->");
document.writeln("	<div class=\'header\'>");
document.writeln("		<a href=\'index.html\'><img src=\'images/logo_01.png\' alt=\'壹杯加咖啡\' class=\'header-left\' /></a>");
document.writeln("		<ul class=\'header-right\'>");
document.writeln("			<li></li>");
document.writeln("			<li></li>");
document.writeln("			<li></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	<!-- 壹杯加咖啡侧边菜单栏模块 -->");
document.writeln("	<nav class=\'menu\'>");
document.writeln("		<div class=\'menu-btn\'>");
document.writeln("			<ul class=\'menu-btn-groups\'>");
document.writeln("				<li></li>");
document.writeln("				<li></li>");
document.writeln("				<li></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<ul class=\'menu-level\' id=\'menu-level\'>");
document.writeln("			<li class=\'menu-level-list first\'>");
document.writeln("				<a href=\'index.html\' class=\'menu-level-links\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>首页</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list has-child\'>");
document.writeln("				<a href=\'javascript:;\' class=\'menu-level-links\' onclick=\'\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>关于品牌</span>");
document.writeln("				</a>");
document.writeln("				<ul class=\'menu-level2\'>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'aboutBrand.html\' class=\'menu-level2-links\'>公司简介</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#brand-introduce\' class=\'menu-level2-links\'>品牌介绍</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'#partner\' class=\'menu-level2-links\'>战略合作伙伴</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list has-child\'>");
document.writeln("				<a href=\'javascript:;\' class=\'menu-level-links\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>品牌项目</span>");
document.writeln("				</a>");
document.writeln("				<ul class=\'menu-level2\'>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'brandProject.html\' class=\'menu-level2-links\'>咖啡连锁店</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#one-space\' class=\'menu-level2-links\'>壹+空间</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#training-college\' class=\'menu-level2-links\'>培训学院</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#coffee-bus\' class=\'menu-level2-links\'>移动咖啡车</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'#online-platform\' class=\'menu-level2-links\'>网上支持平台</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list has-child\'>");
document.writeln("				<a href=\'javascript:;\' class=\'menu-level-links\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>门店形象</span>");
document.writeln("				</a>");
document.writeln("				<ul class=\'menu-level2\'>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'storeImage.html\' class=\'menu-level2-links\'>旗舰店</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'javascript:;\' class=\'menu-level2-links\'>迷你店</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'javascript:;\' class=\'menu-level2-links\'>标准店</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list has-child\'>");
document.writeln("				<a href=\'javascript:;\' class=\'menu-level-links\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>加盟资讯</span>");
document.writeln("				</a>");
document.writeln("				<ul class=\'menu-level2\'>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'joinInformation.html\' class=\'menu-level2-links\'>加盟流程</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#assist-service\' class=\'menu-level2-links\'>协助服务</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list\'>");
document.writeln("						<a href=\'#join-cost\' class=\'menu-level2-links\'>加盟费用</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu-level2-list tail\'>");
document.writeln("						<a href=\'javascript:;\' class=\'menu-level2-links\'>在线预约</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list\'>");
document.writeln("				<a href=\'joinUs.html\' class=\'menu-level-links none-shadow\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>加入我们</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list\'>");
document.writeln("				<a href=\'message.html\' class=\'menu-level-links none-shadow\'>");
document.writeln("					<img src=\'images/title_pointer.png\' alt=\'\' class=\'menu-level-pics\' />");
document.writeln("					<span>留言咨询</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li class=\'menu-level-list\'>");
document.writeln("				<a href=\'javascript:;\' class=\'menu-level-links none-shadow\'>");
document.writeln("					<img src=\'images/shop_icon.png\' alt=\'\' class=\'menu-level-shop\' />");
document.writeln("					<span>壹杯加商城</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</nav>");
document.writeln("	<div>");